# export ANDROID_SDK_HOME="$HOME/Library/Android/sdk"
# export PATH="$ANDROID_SDK_HOME/platform-tools:$PATH"
# export PATH="$ANDROID_SDK_HOME/emulator:$PATH"

# JETBRAINS_TOOLBOX_HOME="$HOME/Library/Application Support/JetBrains/Toolbox"
# export PATH="$JETBRAINS_TOOLBOX_SCRIPTS/scripts:$PATH"
export EDITOR="nvim"

export DISABLE_AUTO_UPDATE=1
export SAM_CLI_TELEMETRY=0

export AMPLIFY_PATH="$HOME/.amplify"
export BUN_INSTALL="$HOME/.bun"
export DOTFILES_PATH="$HOME/dotfiles"
export GEM_HOME="$HOME/.gem"
export LANDO_PATH="$HOME/.lando"
export NVM_DIR="$HOME/.nvm"
export PYENV_ROOT="$HOME/.pyenv"

export PATH="$AMPLIFY_PATH/bin:$PATH"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$GEM_HOME/bin:$PATH"
export PATH="$LANDO_PATH/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"

unset WAYLAND_DISPLAY
