export ANDROID_SDK_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_SDK_HOME/platform-tools:$PATH"
export PATH="$ANDROID_SDK_HOME/emulator:$PATH"

JETBRAINS_TOOLBOX_HOME="$HOME/Library/Application Support/JetBrains/Toolbox"
export PATH="$JETBRAINS_TOOLBOX_SCRIPTS/scripts:$PATH"
