export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  httpie
  rust
)

source $ZSH/oh-my-zsh.sh

export DOTFILES_ZSH_PATH="$HOME/dotfiles/zsh"

source $DOTFILES_ZSH_PATH/zshenv
source $DOTFILES_ZSH_PATH/zshalias

. $DOTFILES_ZSH_PATH/functions.sh
. $DOTFILES_ZSH_PATH/bootstrap.sh

precmd_functions+=(keep_current_path)

fpath+=~/.zfunc
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select
zstyle ':omz:update' mode disabled
